# Generated by Django 3.1.5 on 2021-04-04 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=datetime.datetime(2021, 4, 4, 15, 5, 20, 941959, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
